# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ichiban}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hubert Lepicki"]
  s.date = %q{2010-07-11}
  s.email = %q{hubert.lepicki@amberbit.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/ichiban.rb",
     "lib/ichiban/engine.rb",
     "lib/tasks/rspec.rake",
     "lib/tasks/steak.rake"
  ]
  s.homepage = %q{http://amberbit.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Custom CMS with MongoDB and Mongoid}
  s.test_files = [
    "spec/testapp/config/boot.rb",
     "spec/testapp/config/environment.rb",
     "spec/testapp/config/application.rb",
     "spec/testapp/config/environments/development.rb",
     "spec/testapp/config/environments/production.rb",
     "spec/testapp/config/environments/test.rb",
     "spec/testapp/config/initializers/secret_token.rb",
     "spec/testapp/config/initializers/backtrace_silencers.rb",
     "spec/testapp/config/initializers/mime_types.rb",
     "spec/testapp/config/initializers/session_store.rb",
     "spec/testapp/config/initializers/inflections.rb",
     "spec/testapp/config/routes.rb",
     "spec/testapp/db/seeds.rb",
     "spec/testapp/test/test_helper.rb",
     "spec/testapp/test/performance/browsing_test.rb",
     "spec/testapp/app/controllers/application_controller.rb",
     "spec/testapp/app/helpers/application_helper.rb",
     "spec/acceptance/admin_paths_management_spec.rb",
     "spec/acceptance/user_sign_in_spec.rb",
     "spec/acceptance/admin_assets_management_spec.rb",
     "spec/acceptance/admin_users_management_spec.rb",
     "spec/acceptance/admin_article_management_spec.rb",
     "spec/acceptance/acceptance_helper.rb",
     "spec/acceptance/admin_snippet_management_spec.rb",
     "spec/acceptance/support/paths.rb",
     "spec/acceptance/support/helpers.rb",
     "spec/helpers/paths_helper_spec.rb",
     "spec/spec_helper.rb",
     "spec/models/article_spec.rb",
     "spec/models/paths_spec.rb",
     "spec/models/snippet_spec.rb",
     "spec/models/content_processor_spec.rb",
     "spec/models/user_spec.rb",
     "spec/models/asset_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

